<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFrameworks>net8.0;net9.0;net10.0</TargetFrameworks>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>

		<EnableNETAnalyzers>true</EnableNETAnalyzers>
		<AnalysisLevel>latest</AnalysisLevel>
		<EnforceCodeStyleInBuild>true</EnforceCodeStyleInBuild>

	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Namh.Configuration.Template" Version="1.0.1" />
		<PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.12" />
	</ItemGroup>

</Project>
